#+title: Doom Conf 2021

Planning for an online virtual [[https://github.com/hlissner/doom-emacs][Emacs Doom]] in 2021.

* Overview

Create an online meetup where members of the Doom Emacs community can present
talks relating to Emacs, Doom Emacs, Neovim, and evidently the Expanse.

* Tasks

- [ ] Pick a meeting platform
- [ ] Pick a date
- [ ] Pick a time
- [ ] Organize talk proposals
- [ ] Schedule talks
- [ ] Spread the word

* Talk Proposals

Table below does not reflect order or confirmed talks yet.

| User        | Subject                                                  | Accepted | Duration |
|-------------+----------------------------------------------------------+----------+----------|
| Henrik      | State of Doom                                            | [ ]      |          |
| Flugo       | Mathmatically precise latex-editing skills (expect puns) | [ ]      |          |
| MonadGauge  | The Expanse                                              | [ ]      | 1-hour   |
| MJLBach     | Neovim                                                   | [ ]      |          |
| eccentric-j | How to Read the Fucking Manual                           | [ ]      |          |

** Requests

- Could Henrik discuss the upcoming rewrite?

* When is it?

To be determined.

* Meeting Platform

** Candidates

*** Gathertown

https://gather.town/

*** Calla

https://github.com/capnmidnight/Calla

* Schedule

August maybe?

** Timezone

Lets gather people's timezones and GMT Offsets to try and find a common time
that covers the most amount of people. This site can help find the offset:

https://greenwichmeantime.com/time-zone/usa/eastern-time/


Maybe we can create a formula to calculate how a specific time within a base
timezone aligns with all users?


No one has to specify all information here. User and GMT offset should be enough.

| User        | Location | Timezone | GMT Offset |   |
|-------------+----------+----------+------------+---|
| eccentric-j | NY, USA  | EST      |         -5 |   |


* Is this serious?

Pretty sure. It's not outside of the realm of realistic possibilities to pull
this off but there are certainly some big unknowns and moving parts.

* Contributing

PRs are very welcome
